GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNob2siLCJpYXQiOjE3NDU1MTI5NjcsImV4cCI6MTc0NTUxMjk4Mn0.Aa7DSvh6sy654Y3I8FTAXDlGT-01Pz-cQX_u_8henpk
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNob2siLCJpYXQiOjE3NDU1MTI5MzN9.RuLjqHDSisMbNjk8McZyfCE0tk0SmKyTorHilAon56w"}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name":"ashok"
}